name: pdf
author: David PHAM-VAN <dev.nfet.net@gmail.com>
description: A pdf producer for Dart. It can create pdf files for both web or flutter.
homepage: https://github.com/DavBfr/dart_pdf/tree/master/pdf
repository: https://github.com/DavBfr/dart_pdf
issue_tracker: https://github.com/DavBfr/dart_pdf/issues
version: 3.0.0-nullsafety.0

environment:
  sdk: '>=2.12.0-224.0.dev <3.0.0'

dependencies:
  archive: ^3.0.0-nullsafety
  barcode: ^2.0.0-nullsafety
  crypto: ^3.0.0-nullsafety
  image: ^3.0.0-nullsafety
  meta: ^1.3.0-nullsafety
  path_parsing: ^0.2.0-nullsafety
  vector_math: ^2.1.0-nullsafety
  xml: ^5.0.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
