name: pdf
author: David PHAM-VAN <dev.nfet.net@gmail.com>
description: A pdf producer for Dart. It can create pdf files for both web or flutter.
homepage: https://github.com/davbfr/dart_pdf/pdf
version: 1.0.3

environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  meta: "^1.1.5"
  vector_math: "^2.0.0"

dev_dependencies:
  test: any
