name: pdf
author: David PHAM-VAN <dev.nfet.net@gmail.com>
description: A pdf producer for Dart. It can create pdf files for both web or flutter.
homepage: https://github.com/DavBfr/dart_pdf/tree/master/pdf
repository: https://github.com/DavBfr/dart_pdf
issue_tracker: https://github.com/DavBfr/dart_pdf/issues
version: 1.8.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  meta: ^1.1.5
  vector_math: ^2.0.0
  utf: ^0.9.0
  crypto: ^2.0.6
  archive: ^2.0.10
  barcode: ^1.9.0
  image: ^2.1.13
  path_parsing: ^0.1.4

dev_dependencies:
  test:
  pedantic: 1.9.0
