name: pdf
description: A pdf producer for Dart. It can create pdf files for both web or flutter.
homepage: https://github.com/DavBfr/dart_pdf/tree/master/pdf
repository: https://github.com/DavBfr/dart_pdf
issue_tracker: https://github.com/DavBfr/dart_pdf/issues
screenshots:
  - description: 'Example of a generated document'
    path: example.jpg
topics:
  - pdf
  - printer
  - print
  - printing
  - report
version: 3.11.1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  archive: ^3.1.0
  barcode: ">=2.2.3 <3.0.0"
  bidi: ^2.0.10
  crypto: ^3.0.0
  image: ^4.1.0
  meta: ">=1.3.0 <2.0.0"
  path_parsing: ">=0.2.0 <2.0.0"
  vector_math: ^2.1.0
  xml: ">=6.3.0 <7.0.0"

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ">=1.16.0 <2.0.0"
