name: pdf
author: David PHAM-VAN <dev.nfet.net@gmail.com>
description: A pdf producer for Dart. It can create pdf files for both web or flutter.
homepage: https://github.com/DavBfr/dart_pdf/tree/master/pdf
repository: https://github.com/DavBfr/dart_pdf
issue_tracker: https://github.com/DavBfr/dart_pdf/issues
version: 3.3.1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  archive: ^3.1.0
  barcode: ^2.1.0
  crypto: ^3.0.0
  image: ^3.0.1
  meta: ^1.3.0
  path_parsing: ^0.2.0
  vector_math: ^2.1.0
  xml: ^5.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.0
