name: printing_example
description: Pdf Printing Example

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  printing:
  pdf:

dependency_overrides:
  printing:
    path: ../
  pdf:
    path: ../../pdf

flutter:
  uses-material-design: true
