name: printing_example
description: Pdf Printing Example

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  printing:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  printing:
    path: ..
  pdf:
    path: ../../pdf

flutter:
  uses-material-design: true
