name: printing
author: David PHAM-VAN <dev.nfet.net@gmail.com>
description: Plugin that allows Flutter apps to generate and print documents to android or ios compatible printers
homepage: https://github.com/DavBfr/dart_pdf/tree/master/printing
repository: https://github.com/DavBfr/dart_pdf
issue_tracker: https://github.com/DavBfr/dart_pdf/issues
version: 3.6.1

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: "^1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  pdf: ^1.11.1
  plugin_platform_interface: ^1.0.2
  meta: ^1.1.5
  image: ^2.1.4
  js: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

dependency_overrides:
  pdf:
    path: ../pdf

flutter:
  plugin:
    platforms:
      android:
        package: net.nfet.flutter.printing
        pluginClass: PrintingPlugin
      ios:
        pluginClass: PrintingPlugin
      macos:
        pluginClass: PrintingPlugin
      web:
        fileName: src/printing_web.dart
        pluginClass: PrintingPlugin
