name: printing
author: David PHAM-VAN <dev.nfet.net@gmail.com>
description: Plugin that allows Flutter apps to generate and print documents to android or ios compatible printers
homepage: https://github.com/DavBfr/dart_pdf/tree/master/printing
repository: https://github.com/DavBfr/dart_pdf
issue_tracker: https://github.com/DavBfr/dart_pdf/issues
version: 5.0.0-nullsafety.2

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  ffi: ">=0.2.0-nullsafety <2.0.0"
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image: ^3.0.0-nullsafety
  js: ^0.6.3-nullsafety
  meta: ^1.3.0-nullsafety
  pdf: ^3.0.0-nullsafety
  plugin_platform_interface: ^1.1.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety

dependency_overrides:
  pdf:
    path: ../pdf

flutter:
  plugin:
    platforms:
      android:
        package: net.nfet.flutter.printing
        pluginClass: PrintingPlugin
      ios:
        pluginClass: PrintingPlugin
      linux:
        pluginClass: PrintingPlugin
      macos:
        pluginClass: PrintingPlugin
      web:
        fileName: src/printing_web.dart
        pluginClass: PrintingPlugin
      windows:
        pluginClass: PrintingPlugin
