name: printing
author: David PHAM-VAN <dev.nfet.net@gmail.com>
description: Plugin that allows Flutter apps to generate and print documents to android or ios compatible printers
homepage: https://github.com/DavBfr/dart_pdf/tree/master/printing
repository: https://github.com/DavBfr/dart_pdf
issue_tracker: https://github.com/DavBfr/dart_pdf/issues
version: 1.3.5

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: "^1.2.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: "^1.3.3"

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  pdf:
    path: ../pdf

flutter:
  plugin:
    androidPackage: net.nfet.flutter.printing
    pluginClass: PrintingPlugin
