name: pdf_widget_wrapper
description: >
  Plugin that allows embedding of Flutter Widgets into a PDF document.
homepage: https://github.com/DavBfr/dart_pdf/tree/master/widget_wrapper
repository: https://github.com/DavBfr/dart_pdf
issue_tracker: https://github.com/DavBfr/dart_pdf/issues
version: 1.0.2

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.18.0-1.0.pre.23<3.19.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.0

dependency_overrides:
  pdf:
    path: ../pdf

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
