name: pdf_widget_wrapper
description: >
  Plugin that allows embedding of Flutter Widgets into a PDF document.
homepage: https://github.com/DavBfr/dart_pdf/tree/master/widget_wrapper
repository: https://github.com/DavBfr/dart_pdf
issue_tracker: https://github.com/DavBfr/dart_pdf/issues
version: 1.0.4

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.20.0-7.0.pre.48"

dependencies:
  flutter:
    sdk: flutter
  pdf:
    git:
      url: https://github.com/hbatalhaStch/dart_pdf.git
      path: pdf

dependency_overrides:
  pdf:
    path: ../pdf

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# flutter:
