name: pdf_widget_wrapper
description: >
  Plugin that allows embedding of Flutter Widgets into a PDF document.
homepage: https://github.com/DavBfr/dart_pdf/tree/master/widget_wrapper
repository: https://github.com/DavBfr/dart_pdf
issue_tracker: https://github.com/DavBfr/dart_pdf/issues
version: 1.0.4

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.20.0-7.0.pre.48"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.0

dependency_overrides:
  pdf:
    path: ../pdf

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
