name: printing_example
description: Pdf Printing Example

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  open_file:
  path_provider:
  printing:
  url_launcher:

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test:

dependency_overrides:
  pdf:
    path: ../pdf
  printing:
    path: ../printing

flutter:
  uses-material-design: true
  assets:
    - assets/
