name: printing_demo
description: Pdf Printing Demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  open_file:
    git:
      url: https://github.com/orevial/open_file
      ref: null-safety-migration
  path_provider:
  printing:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

dependency_overrides:
  pdf:
    path: ../pdf
  printing:
    path: ../printing

flutter:
  uses-material-design: true
  assets:
    - assets/
