name: printing_demo
description: Pdf Printing Demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  open_file: ^3.2.1
  path_provider: ^2.0.2
  printing: ^5.3.0
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  test: ^1.16.5

dependency_overrides:
  pdf:
    path: ../pdf
  printing:
    path: ../printing

flutter:
  uses-material-design: true
  assets:
    - assets/
