name: printing_demo
description: Pdf Printing Demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  open_file: ^3.2.1
  path_provider: ^2.0.12
  pdf:
  printing:
  url_launcher: ^6.1.8
  vector_math: ^2.1.4

dev_dependencies:
  # flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test: ^1.22.0

dependency_overrides:
  pdf:
    path: ../pdf
  printing:
    path: ../printing

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: "app-logo.png"
  remove_alpha_ios: true
  android:
    generate: true
  ios:
    generate: true
  web:
    generate: true
  windows:
    generate: true
