name: Dart CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Enable Linux for flutter
        run: flutter config --enable-linux-desktop
      - name: Update repo
        run: sudo apt update
      - name: Install utils
        run: sudo apt install poppler-utils imagemagick clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Run analysis
        run: make analyze
      - name: Run tests
        run: make test
      - name: Run readme tests
        run: make test-readme
      - name: Verify that nothing changed
        run: test -z "$(git status --porcelain)"
      - name: Push to codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Prepare build
        run: cd printing/example; flutter create -t app --no-overwrite --org net.nfet --project-name example .
      - name: Build example for Linux
        run: cd printing/example; flutter build -v linux
      - name: Build example for Android
        run: cd printing/example; flutter build -v apk
      - name: Build demo for Web
        run: cd demo; flutter build -v web

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Enable Windows for flutter
        run: flutter config --enable-windows-desktop
      - name: Prepare build
        run: cd printing/example; flutter create -t app --no-overwrite --org net.nfet --project-name example .
      - name: Build example for Windows
        run: cd printing/example; flutter build -v windows

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Enable macOS for flutter
        run: flutter config --enable-macos-desktop
      - name: Prepare build
        run: cd printing/example; flutter create -t app --no-overwrite --org net.nfet --project-name example .
      - name: Build example for macOS
        run: cd printing/example; flutter build -v macos
      # - name: Build example for iOS
      #   run: cd printing/example; flutter build -v ios
